language: node_js
node_js:
    - "10.15.3"

sudo: false

#cache
cache:
  directories:
    - "node_modules"

notifications:
  # 钉钉机器人消息推送部署结果
  webhooks:
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=${DINGDING_ACCESS_TOKEN}
    on_success: change
    on_failure: always

  # 邮件发送部署结果通知
  email:
    recipients:
      - AdolfYin@gmail.com
    on_success: always
    on_failure: always

# S: Build Lifecycle
before_install:
  - sudo apt-get install libnotify-bin

install:
  - npm install
#  - gem install travis
#  - travis login --pro --github-token ${GH_TOKEN}

before_script:
  - export TZ='Asia/Shanghai'
  - npm install -g gulp
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g

after_success:
   是在Travis中配置token的名称
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
 - ./_travis.sh
 - cd ./public
 - git init
 - git config user.name "${USER_NAME}" # 修改name
 - git config user.email "${USER_EMAIL}" # 修改email
 - git add .
 - git commit -m "Travis CI Auto Builder"
 - git push --force --quiet "https://${REPO_TOKEN}@${GITHUB_URL}" master:master # GH_TOKEN


# E: Build LifeCycle

# 设置只监听哪个分支 
branches:
  only:
    - source
env:
 global:
   #- GH_REF: github.com/shenliyang/shenliyang.github.io.git
   #- GITEE_REF: gitee.com/shenliyang/shenliyang.git

